### PR TITLE
add PHP8 support

### PR DESCRIPTION
**Pull request by Gummibeer**

### CODE REVIEW

**Comment by freekmurze** [comment]
Seems like the PHP 8 are failing, could you take a look at that?

**Comment by Gummibeer** [comment]
Yeah, seems like some deprecated  methods somewhere in the HTML parser/lib. 🤔
Could be that a spatie/crawler upgrade is required.

**Comment by Gummibeer** [comment]
It's only the `lowest` - so I will have to check which symfony/dom-crawler fixed this PHP8  issue and add it as minimum for the old spatie/crawler v4.

**Comment by fachcraftim** [comment]
hey @Gummibeer any news on this?

**Comment by Gummibeer** [comment]
@freekmurze could you please release this commit https://github.com/spatie/crawler/commit/0b7c9a2ac79d98796dc0c4750a9ef7b8614804d8 as `4.7.7`?

**Comment by Gummibeer** [comment]
converted to draft as it uses a branch dependency right now.

**Comment by Elhebert** [comment]
@Gummibeer @freekmurze any status on this?

**Comment by jeffhunt00** [comment]
Crawler is up to 6.0.X now. It would be great to get an update that supports PHP8 and the latest spatie/crawler :)

**Comment by freekmurze** [comment]
Seems like all tests are passing now for this one.

@Gummibeer Do you want to continue your work on this and add support for the latest crawlers? Or do you want me to finish this one?

**Comment by Gummibeer** [comment]
Hey Freek, I'm sorry that I don't have time to proceed here right now.
So anyone can take on this, reuse my PR or even start a fresh one. 😉

**Comment by freekmurze** [comment]
No apologies needed, I'll take care of this 👍

**Pull request merged**
